services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devpulse
      POSTGRES_PASSWORD: devpulse123
      POSTGRES_DB: devpulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://devpulse:devpulse123@db:5432/devpulse
      GITLAB_TOKEN: c88176446aad7b39b8f406f426ee33f5c6add46fb7ea6e57210e6664d290d473
    depends_on:
      - db

  nestjs:
    build: ../devpulse-gateway
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: devpulse
      DB_PASSWORD: devpulse123
      DB_NAME: devpulse_gateway
      JWT_SECRET: devpulse_secret_key_2026
      FASTAPI_URL: http://fastapi:8000
    depends_on:
      - db
      - fastapi

volumes:
  postgres_data: